<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
        <title>KumbiaPHP web &amp; App Framework</title>

        <!-- Modernizr -->
        <?php echo Tag::js("groundwork/libs/modernizr-2.6.2.min.js") ?>
        <!-- jQuery -->
        <?php echo Tag::js("groundwork/libs/jquery-1.10.2.min.js") ?>
        <!-- GroundworkCSS -->
        <?php Tag::css('groundwork/groundwork') ?>
        <!--[if IE]>
        <link type="text/css" rel="stylesheet" href="./css/groundwork-ie.css">
        <![endif]-->
        <!--[if IE 7]>
        <link type="text/css" rel="stylesheet" href="./css/font-awesome-ie7.min.css">
        <![endif]-->
        <?php echo Html::includeCss() ?>
    </head>
    <body>
        <header class="white band padded">
            <div class="container">
                <h2 class="AverageSans">Bitacora</h2>
                <nav class="nav inline menu gap-top" data-label="Menu"><a href="#" class="menu-toggle"><i class="icon-reorder"></i></a>
                    <ul>
                        <li><a href="./home.html"><i class="icon-home"></i> Home</a></li>
                        <li class="menu"><a href="#">Example Layouts</a>
                            <ul>
                                <li><a href="./layout-1.html">Layout 1</a></li>
                            </ul>
                        </li>
                        <li class="menu"><a href="#">Example Components Usage</a>
                            <ul>
                                <li><a href="./grid.html" title="Responsive grid system, grid adapters and helpers">Grid</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </header> 
        <div id='content' class="container">
            <?php View::content(); ?>
        </div>
        <?php View::partial('footer') ?>
    </body>
</html>
